# Generated by Django 2.2.7 on 2019-11-27 02:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField(verbose_name='用户编号')),
                ('bookId', models.IntegerField(verbose_name='图书编号')),
                ('boDate', models.DateTimeField(auto_now_add=True, verbose_name='借书时间')),
                ('reDate', models.DateTimeField(null=True, verbose_name='还书时间')),
                ('returnFlag', models.BooleanField(default=False, verbose_name='归还标志')),
            ],
            options={
                'verbose_name': '借阅',
                'verbose_name_plural': '借阅',
            },
        ),
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='类别名')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '类别',
                'verbose_name_plural': '类别',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField(verbose_name='用户编号')),
                ('bookId', models.IntegerField(verbose_name='图书编号')),
                ('content', models.TextField(verbose_name='评论内容')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField(verbose_name='用户编号')),
                ('bookId', models.IntegerField(verbose_name='图书编号')),
                ('subDate', models.DateTimeField(auto_now_add=True, verbose_name='预定日期')),
                ('number', models.IntegerField(default=1, verbose_name='数量')),
                ('successFlag', models.BooleanField(default=False, verbose_name='完成预约标志')),
            ],
            options={
                'verbose_name': '预定',
                'verbose_name_plural': '预定',
            },
        ),
        migrations.CreateModel(
            name='CommonUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickyName', models.CharField(blank=True, max_length=50, verbose_name='昵称')),
                ('cate', models.BooleanField(default=False, verbose_name='类别')),
                ('faculty', models.CharField(blank=True, default='undefine', max_length=20, verbose_name='系别')),
                ('bookBorrow', models.IntegerField(default=0, verbose_name='已借图书数目')),
                ('bookSub', models.IntegerField(default=0, verbose_name='已预约图书数目')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=13, unique=True, verbose_name='ISBN')),
                ('title', models.CharField(max_length=200, verbose_name='书名')),
                ('subtitile', models.CharField(blank=True, max_length=200, verbose_name='副标题')),
                ('pages', models.IntegerField(blank=True, verbose_name='页数')),
                ('author', models.CharField(blank=True, max_length=60, verbose_name='作者')),
                ('translator', models.CharField(blank=True, max_length=60, verbose_name='译者')),
                ('price', models.CharField(blank=True, max_length=60, verbose_name='定价')),
                ('publisher', models.CharField(blank=True, max_length=200, verbose_name='出版社')),
                ('pubdate', models.CharField(blank=True, max_length=60, verbose_name='出版日期')),
                ('cover_img', models.ImageField(blank=True, upload_to='category', verbose_name='封面')),
                ('summary', models.TextField(blank=True, max_length=2000, verbose_name='内容简介')),
                ('author_intro', models.TextField(blank=True, max_length=2000, verbose_name='作者简介')),
                ('number', models.IntegerField(default=0, verbose_name='库存数量')),
                ('catelog', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lms.Catalog')),
            ],
            options={
                'verbose_name': '图书',
                'verbose_name_plural': '图书',
                'ordering': ('pubdate',),
            },
        ),
    ]
